apiVersion: v1
kind: Service
metadata:
  name: story-service
spec: 
  selector:  # selector selects the to be control pods
    app: story
  type: LoadBalancer
  ports: 
    - protocol: 'TCP'
      port: 80
      targetPort: 3000