apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer    #ClusterIP ==> (default) internal cluster not for outside world && #NodePort ==> can reach from outside but using ip address
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080