apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template: 
    metadata: 
      labels:
        app: users
    spec:
      containers:
        # 1st container
        - name: users
          image: etevabharat/kub-demo-users:latest
          env: 
            - name: AUTH_ADDRESS
              value: localhost
        #   # 2nd container in same pod
        - name: auth
          image: etevabharat/kub-demo-auth:latest
          