apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: story
  template: 
    metadata:
      labels:
        app: story
    spec: 
      containers: 
        - name: story
          image: etevabharat/kub-data-demo:2
          env:
            - name: STORY_FOLDER
              # value: 'story'
              valueFrom: 
                configMapKeyRef: 
                  name: data-store-env # metadataName
                  key: folder
          volumeMounts:
            - mountPath: /app/story
              name: story-volume
      volumes: 
        - name: story-volume
          # emptyDir: {} # volume Type ==> pod specific & data survive when container restart but can not share with multiple pods/container
          # hostPath: # like bindMount ==> not pod specific but it is node specific
          #   path: /data
          #   type: DirectoryOrCreate
          persistentVolumeClaim: 
            claimName: host-pvc
          
